# **Проверка качества данных**

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
from datetime import datetime

Задание 1: Проверка целостности данных.
Используйте набор данных о продажах и проверьте, заполнены ли все необходимые поля. Если обнаружены пропущенные значения, определите, какой процент они составляют от общего количества данных.

Набор данных для использования: "Online Retail" на Kaggle. Этот набор данных представляет собой транзакции, произошедшие в период с декабря 2010 по октябре 2011 года и зарегистрированные розничной компанией из Великобритании.
Ссылка: https://www.kaggle.com/mashlyn/online-retail-ii-uci

In [ ]:
data = pd.read_csv('data/online_retail_II.csv')
data.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188661 entries, 0 to 188660
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      188661 non-null  object
 1   StockCode    188661 non-null  object
 2   Description  187303 non-null  object
 3   Quantity     188661 non-null  int64
 4   InvoiceDate  188661 non-null  object
 5   Price        188661 non-null  float64
 6   Customer ID  144713 non-null  float64
 7   Country      188661 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 11.5+ MB

Consider the number of missing values according to each column

In [ ]:
null_values = data.isna().sum()
null_values

Invoice            0
StockCode          0
Description     1358
Quantity           0
InvoiceDate        0
Price              0
Customer ID    43948
Country            0
dtype: int64

Consider the number of non-zero values according to each column

In [ ]:
non_null_values = data.notna().sum()
non_null_values

Invoice        188661
StockCode      188661
Description    187303
Quantity       188661
InvoiceDate    188661
Price          188661
Customer ID    144713
Country        188661
dtype: int64

The number of missing values is

In [ ]:
null_values_count = null_values.sum()
null_values_count

45306

The number of non-empty values is

In [ ]:
non_null_values_count = non_null_values.sum()
non_null_values_count

1463982

Thus, the percentage of missing values in relation to the total amount of data is

In [ ]:
null_values_count / non_null_values_count * 100

3.0947101808628794

Задание 2: Проверка консистентности данных.
Рассмотрите набор данных о климате и проверьте, соблюдаются ли форматы дат во всех записях.

Набор данных для использования: "Climate Change: Earth Surface Temperature Data" на Kaggle.

Ссылка: https://www.kaggle.com/berkeleyearth/climate-change-earth-surface-temperature-data

In [ ]:
data = pd.read_csv('data/GlobalTemperatures.csv')
data.head()

,dt,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
0,1750-01-01,3.034,3.574,NaN,NaN,NaN,NaN,NaN,NaN
1,1750-02-01,3.083,3.702,NaN,NaN,NaN,NaN,NaN,NaN
2,1750-03-01,5.626,3.076,NaN,NaN,NaN,NaN,NaN,NaN
3,1750-04-01,8.490,2.451,NaN,NaN,NaN,NaN,NaN,NaN
4,1750-05-01,11.573,2.072,NaN,NaN,NaN,NaN,NaN,NaN

Let's define a method for detecting an incorrect date.

In [ ]:
data['dt'] = pd.to_datetime(data['dt'], errors='coerce')
incorrect_dates = data[data['dt'].isna()]

incorrect_dates

Empty DataFrame
Columns: [dt, LandAverageTemperature, LandAverageTemperatureUncertainty, LandMaxTemperature, LandMaxTemperatureUncertainty, LandMinTemperature, LandMinTemperatureUncertainty, LandAndOceanAverageTemperature, LandAndOceanAverageTemperatureUncertainty]
Index: []

Thus, there are no incorrectly set dates in the dataframe.

Some dates in the dataframe were manually changed. Uploading a dataframe with incorrect dates

In [ ]:
data = pd.read_csv('data/GbalTempIncorr.csv')
data.head(11)

,dt,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
0,1750-01-01,3.034,3.574,NaN,NaN,NaN,NaN,NaN,NaN
1,175002-01,3.083,3.702,NaN,NaN,NaN,NaN,NaN,NaN
2,1750-03-01,5.626,3.076,NaN,NaN,NaN,NaN,NaN,NaN
3,1750-04-01,8.490,2.451,NaN,NaN,NaN,NaN,NaN,NaN
4,1750-05-01,11.573,2.072,NaN,NaN,NaN,NaN,NaN,NaN
5,1750-06-01,12.937,1.724,NaN,NaN,NaN,NaN,NaN,NaN
6,1750-07,15.868,1.911,NaN,NaN,NaN,NaN,NaN,NaN
7,1750-08-01,14.750,2.231,NaN,NaN,NaN,NaN,NaN,NaN
8,1750-09-01,11.413,2.637,NaN,NaN,NaN,NaN,NaN,NaN
9,1750-10-01,6.367,2.668,NaN,NaN,NaN,NaN,NaN,NaN
10,19034-10-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data['dt'] = pd.to_datetime(data['dt'], errors='coerce')
incorrect_dates = data[data['dt'].isna()]

incorrect_dates

,dt,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
1,NaT,3.083,3.702,NaN,NaN,NaN,NaN,NaN,NaN
6,NaT,15.868,1.911,NaN,NaN,NaN,NaN,NaN,NaN
10,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

As you can see, the function correctly identified the incorrectly set dates.

Задание 3: Проверка актуальности данных.
Анализируя набор данных о твитах, проверьте даты публикации твитов и определите, какие из них актуальны на текущий момент.

Набор данных для использования: "COVID19 Tweets" на Kaggle, включающий твиты о пандемии COVID-19.
Ссылка: https://www.kaggle.com/gpreda/covid19-tweets

In [22]:
data = pd.read_csv('data/covid19_tweets.csv')
data.head()

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet
0,ᏉᎥ☻լꂅϮ,astroworld,wednesday addams as a disney princess keepin i...,2017-05-26 05:46:42,624,950,18775,False,2020-07-25 12:27:21,If I smelled the scent of hand sanitizers toda...,NaN,Twitter for iPhone,False
1,Tom Basile 🇺🇸,"New York, NY","Husband, Father, Columnist & Commentator. Auth...",2009-04-16 20:06:23,2253,1677,24,True,2020-07-25 12:27:17,Hey @Yankees @YankeesPR and @MLB - wouldn't it...,NaN,Twitter for Android,False
2,Time4fisticuffs,"Pewee Valley, KY",#Christian #Catholic #Conservative #Reagan #Re...,2009-02-28 18:57:41,9275,9525,7254,False,2020-07-25 12:27:14,@diane3443 @wdunlap @realDonaldTrump Trump nev...,['COVID19'],Twitter for Android,False
3,ethel mertz,Stuck in the Middle,#Browns #Indians #ClevelandProud #[]_[] #Cavs ...,2019-03-07 01:45:06,197,987,1488,False,2020-07-25 12:27:10,@brookbanktv The one gift #COVID19 has give me...,['COVID19'],Twitter for iPhone,False
4,DIPR-J&K,Jammu and Kashmir,🖊️Official Twitter handle of Department of Inf...,2017-02-12 06:45:15,101009,168,101,False,2020-07-25 12:27:08,25 July : Media Bulletin on Novel #CoronaVirus...,"['CoronaVirusUpdates', 'COVID19']",Twitter for Android,False

In [23]:
data['date'] = pd.to_datetime(data['date'], errors = 'coerce')

Let's enter a variable responsible for today's date.

In [24]:
actual_date = datetime.today()
actual_date

datetime.datetime(2024, 12, 22, 21, 51, 16, 350432)

Define a method that will return True or False, depending on whether the date is current. For example, let's set the standard date relevance value to 30 days.

In [25]:
def is_actual_date(object_date, actual_date, days=30):
    return (actual_date - object_date).days <= days

We add a new column to the source data, which indicates whether the date is current.

In [27]:
data['is_actual'] = data.date.apply(lambda object_date: is_actual_date(object_date, actual_date))
data.head()

,user_name,user_location,user_description,user_created,user_followers,user_friends,user_favourites,user_verified,date,text,hashtags,source,is_retweet,is_actual
0,ᏉᎥ☻լꂅϮ,astroworld,wednesday addams as a disney princess keepin i...,2017-05-26 05:46:42,624,950,18775,False,2020-07-25 12:27:21,If I smelled the scent of hand sanitizers toda...,NaN,Twitter for iPhone,False,False
1,Tom Basile 🇺🇸,"New York, NY","Husband, Father, Columnist & Commentator. Auth...",2009-04-16 20:06:23,2253,1677,24,True,2020-07-25 12:27:17,Hey @Yankees @YankeesPR and @MLB - wouldn't it...,NaN,Twitter for Android,False,False
2,Time4fisticuffs,"Pewee Valley, KY",#Christian #Catholic #Conservative #Reagan #Re...,2009-02-28 18:57:41,9275,9525,7254,False,2020-07-25 12:27:14,@diane3443 @wdunlap @realDonaldTrump Trump nev...,['COVID19'],Twitter for Android,False,False
3,ethel mertz,Stuck in the Middle,#Browns #Indians #ClevelandProud #[]_[] #Cavs ...,2019-03-07 01:45:06,197,987,1488,False,2020-07-25 12:27:10,@brookbanktv The one gift #COVID19 has give me...,['COVID19'],Twitter for iPhone,False,False
4,DIPR-J&K,Jammu and Kashmir,🖊️Official Twitter handle of Department of Inf...,2017-02-12 06:45:15,101009,168,101,False,2020-07-25 12:27:08,25 July : Media Bulletin on Novel #CoronaVirus...,"['CoronaVirusUpdates', 'COVID19']",Twitter for Android,False,False

In [28]:
data['is_actual'].value_counts()

is_actual
False    179108
Name: count, dtype: int64

In other words, all the data has an outdated date. Let's create a synthetic date, which we will consider today.

In [29]:
synthetic_date = datetime(2020, 7, 25, 15, 50, 45, 342380)
synthetic_date

datetime.datetime(2020, 7, 25, 15, 50, 45, 342380)

Now let's try to determine whether the date is relevant, considering the synthetic date as today. We will assume that the date will be relevant if it deviates by no more than a day from today's date.

In [31]:
data['is_actual'] = data.date.apply(lambda object_date: is_actual_date(object_date, synthetic_date, 1))
data['is_actual'].value_counts()

is_actual
True    179108
Name: count, dtype: int64

That is, all data has an actual date.

Задание 4: Проверка полноты данных.
Рассмотрите набор данных о заболеваемости раком, проанализируйте, приведены ли данные по всем странам или некоторые из них отсутствуют.
Набор данных для использования: "Global Cancer Statistics 2018 (GLOBOCAN 2018)" на Kaggle.
Ссылка: https://www.kaggle.com/ashkhagan/global-cancer-statistics-2018-globocan-2018

In [32]:
data = pd.read_csv('data/GblCancerbyCountry.csv')
data.head()

  Both sexes      Number  ASR/100,000
0      World  18,094,716        190.0
1    Denmark      39,996        334.9
2    Ireland      27,067        326.6
3    Belgium      74,162        322.8
4    Hungary      62,399        321.6

In [39]:
!pip install country_list
from country_list import countries_for_language

Collecting country_list
  Downloading country_list-1.1.0-py3-none-any.whl.metadata (3.9 kB)
Downloading country_list-1.1.0-py3-none-any.whl (1.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 15.4 MB/s eta 0:00:00
Installing collected packages: country_list
Successfully installed country_list-1.1.0

Consider the number of unique countries from the dataset

In [40]:
len(data['Both sexes'].unique())

186

Downloading a list of all countries in English from the library.

In [41]:
countries = dict(countries_for_language('en'))
countries_list = list(countries.values())
countries_list[:5]

['Afghanistan', 'Åland Islands', 'Albania', 'Algeria', 'American Samoa']

Consider the total number of countries from the library

In [42]:
len(countries_list)

249

Let's define a function that returns a dictionary of the form {country: boolean}, where the value is responsible for whether the country is in the dataframe or not.

Note: In this case, the dataframe also contains countries that are not in the countries_list list from the library. Therefore, both lists are combined inside the function.

In [43]:
def count_data_by_countries(data : pd.DataFrame):
    library_countries = dict(countries_for_language('en'))
    library_countries_list = list(library_countries.values())
    dataframe_countries_list = data['Both sexes'].tolist()

    all_countries_list = dataframe_countries_list + library_countries_list

    countries_statistis = dict.fromkeys(countries_list, False)

    for country in dataframe_countries_list:
        if country in all_countries_list:
            countries_statistis[country] = True

    return countries_statistis

In [44]:
countries_statistic = count_data_by_countries(data)

Output the first 5 values of the received dictionary

In [45]:
{k: countries_statistic[k] for k in list(countries_statistic)[:5]}

{'Afghanistan': True,
 'Åland Islands': False,
 'Albania': True,
 'Algeria': True,
 'American Samoa': False}

Consider the number of all values in the resulting dictionary

In [46]:
len(countries_statistic.keys())

267

Consider the number of missing countries in the dataframe

In [48]:
missed_countries = [country for country in countries_statistic.keys() if countries_statistic[country] == False]
len(missed_countries)

81